### ISSUE TITLE
Add other Schema Registry serializers

### ISSUE THREAD

**Issue by OneCricketeer** [bakdata/kafka-brute-force-serde#4]
Current version only supports Avro, Strings, and Bytes. 

Should Protobuf and JSONSchema now be supported, as they are by the Confluent Schema Registry.

**Comment by torbsto** [comment]
Hi, our plan is to expose the list of SerDes and Converters through a configuration, then everyone can set them to their needs. A corresponding PR will follow soon.

**Comment by torbsto** [comment]
We've released v1.2.0, which allows you to [configure the list of serdes and converters](https://github.com/bakdata/kafka-brute-force-serde#configuration) with `brute.force.serdes` and `brute.force.converters` respectively.

**Comment by OneCricketeer** [comment]
Thanks for the update!
